syntax = "proto3";

package auth;

service AuthService {
  // existing
  rpc GetAllUsers (Empty) returns (UserList);

  // 🔥 new (for restaurant, grocery, medical)
  rpc GetUserEmails (UserPaginationRequest) returns (PaginatedUserResponse);
}

message Empty {}

message User {
  string id = 1;
  string name = 2;
}

message UserList {
  repeated User users = 1;
}

/* ---------- NEW ---------- */

message UserPaginationRequest {
  int32 page = 1;
  int32 limit = 2;
  string search = 3;
}

message UserEmail {
  string email = 1;
}

message PaginatedUserResponse {
  repeated UserEmail data = 1;
  int32 total = 2;
  int32 page = 3;
  int32 limit = 4;
}
