version: "3.9"

services:
  # ============================
  # 🗄️ MongoDB Database
  # ============================
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: userprebook
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand({ ping: 1 })' mongodb://localhost:27017/userprebook --quiet || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  # ============================
  # 🟢 Redis
  # ============================
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  # ============================
  # 🔐 Auth Service (NestJS + gRPC)
  # ============================
  authservice:
    container_name: authservice
    build:
      context: .
      dockerfile: ./apps/authservice/Dockerfile
    restart: on-failure
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "9000:9000"    # HTTP
      - "50051:50051"  # gRPC
    env_file:
    - .env.docker
    networks:
      - app-network

# ============================
# 💾 Volumes
# ============================
volumes:
  mongo-data:
    driver: local

# ============================
# 🌐 Network
# ============================
networks:
  app-network:
    driver: bridge
